#+TITLE: Mark Johnson interviewed by Heather Landy, Quartz at Work from Home

* Present Forward Fallacy

This is in the sense of business planning.

"Businesses can be extended from the way things work today indefinitely"

But new tech or events could unstick possibilities!

* Future Back Thinking

This has parallels to design thinking.  To develop a point of view of
the future in the right way, let go of the present and past.  Bring
some core things but open up the mind.

"Clean sheet thinking" as opposed to what things are like today.

Be systemic, asking "what could be" as opposed to what is.

* How far out to the future should you be thinking?

Putting aside the current crisis b/c that limits our thinking.

But, recognizing that things can arise that are disruptive, we want to
get outside of the volatile, complex, uncertain world to get to
something that is like a north star.

This is typically 5 to 10 years.  More than 75% of companies don't
think beyond 5 years.  But a defense or pharmaceutical company may
think 15 years ahead.

We do it through dialogue.  You have to talk it through. 

* How do you balance thinking ahead and break through things with the core of your existing business?

Most businesses should spent 90% of their time on "present forward,
operate and execute."

But how to put 10 or 20% of time into exploring, and envisioning how
you fit in that, and bring back to today the validity of what you have
envisioned.  This is a different headspace.

But we aren't even seeing leadership teams bend 5% on envisioning
"what could be" and "what does the future really mean?"

* Then you have an Elon Musk... they seem to live in the future

So much potential but many problems in the day-to-day.

* What is the connective tissue between the present and future thinking?

Can you get to "Affordable electic car, iPhone" without future-back
thinking?

Trying to get past core and adjacent growth, we found that top
management wasn't in the right headspace.  

We have found so few companies other than Amazon that can go around
creating whole new business models.  We're not thinking in the right
way.  Plenty of companies coming up with ideas for products, services,
and business models, but they are not getting implemented.

So, often in less than a year or 2 they are starved of core resources.
So they don't sustain through these Valley of Death moments.

E.g., locomotive technology: the first one had stage coaches behind
it.

* We have a mindset to say "take data, make decisions"

Including to manage it with big data.  This helps present forward.  

Leaders can't imagine giving things up.  So they need to delegate, or
simply carve out.  "We are going to carve out at least a day every 3
months to spend on the art of the possible, or 3-4 hours a week as a
leadership team."

We also have a strong availability bias, and hyperbolic discounting of
the future.

There's a lot of scepticism about what you can do with the future.
But it's not about creating a photo, but an impressionist painting.

Every team that does this will gain some insights that they can apply
now, which they wouldn't have without a long-term horizon.

* Can you designate people to be leaders in looking outward?

I don't think everyone has to be involve at the same level of detail.
But it does need to involve CEO, CSO, CFO at some point.

You need to align the leadership team.  Not just on core work.

So, you can't delegate this completely.  *A good chunk of the team has to do this together.*

* Are managers and leaders incentivised to think about this?

They tend to be paid on past performance.  This is a real problem.

Stock performance is based on future earnings, but rewards are often
in the rear-view mirror.

So this needs to change.  Leaders should be rewarded based on what
they learn.

E.g., Microsoft shifting from "know-it-alls" to "learn-it-alls".  This
has created an anchor in that organization.

* What are some of the exercises you recommend?

E.g., a weird meeting that you and your colleagues had in Australia to
understand *the future of education.*

What is the way to get in the mind space?  We prescribe strategic
dialogues.  Bring the right group of people who have resource
allocation decision making, and allow them to diverge before they
converge.  

"Differences need to come into close contact for learning to occur"

In Australia, we gave them 5 themes and used a process to wrestle with
the trends underneath them, in order to come up with assumptions.

We got "optimists" and "pessimists" to describe how it would play out
(to be beneficial or detrimental).  Then used these different "pure
tones" to come together and think about how to place themselves.

What are the kinds of experiments they could do today?

* "How far forward does your company think"

1-3 years, 3-5... maybe 10% think more than 5 years.

* How do you adjust your business processes to work with your new vision?

If you think about developing the vision, it's more than just a vision
statement.  It's a way to think about the future.

E.g., Apple's vision in the middle of the dot-com crisis was to look
10 years out and imagine the "digital hub".  They connecting with and
then creating digital devices.

Having peered into the future... convert from being a story-teller and
artist into being an engineer.

"Core, adjacent, and new"

What do you want that to be, from revenue and impact points of view?

What milestones will you need to achieve to get there?

This brings you to a portfolio of things to do.  To possibly leverage
to other markets, keeping a core... but have a balanced portfolio that
reflects the future vision.

Then, figure out how to program that.  How to govern when people are
busy on the core efforts?  Create the right kinds of autonomy.

It's going to be more of an incubation effort.

You change business processes by linking vision to engineering, making
both core and new happen, and staying good at learning.  
*Learning is the underpinning of all this!*

Learning has to be in the fore-front if we are going to achieve these beyond-the-core
breakthroughs.

* How much of what you're saying applies to startups?

First, on the startups, I couldn't say more strongly: it absolutely does.

A startup usually has a passionate entrepreneur who believes something can be created but who doesn't have access to all the resources.

Do they have an inspiring vision about what they can/want to incubate in 5 years.

If you can't see out there and believe in it and have others believe in it, you won't get there.

So the vision piece applies.

The other part is, what do I have to believe in order for the hopeful story to be realised?

This gets you into the model of making assumptions.  Instead of making a business plan, you really need a learning plan.

"For this to happen what needs to become true."

What needs to be tested first to get me on the path to my future vision?

Doing this future back is incredibly helpful.  The process of doing that will help to make the roadmap you need to develop.

* What about B2B businesses, vs B2C?  Is it harder to forecast?

It may depend.  None of this is easy.  But I guarantee you can pull insights out of it.

The B2B has to *think about its customer's customer.* Even if it
doesn't have full influence on it.

Selling to WalMart, Amazon etc., they say "the customer is boss."

* If you are in a business that is dealing with disruption...

Next 3 years are thinking about keeping the ship afloat.  How to make
the future come faster?

"Repair the roof when the sun is shining."

As the core business becomes under threat, it's hard not to just
hunker down.  But in this situation you then have to look at the other
side.  Where do you want to be?  Not just addressing the threat.

What are the opportunities that could fill the gap for the things that
are going to be disrupted?

We can't afford to /not/ carve out some of our time.  We will need to
re-allocate for the business unit that will go past the unit that will
no longer exist.

"Every business has a theory, and sooner or later that theory no
longer works."

You need to figure out a way to latch on to the new theory, while
still maximizing things like cash flow that will fund the future.

"One foot in the lifeboat, one in the ship."  Still you have to start
with vision and where you want to move towards.

* Women are better at thinking future, or having capacity for thinking complex.

I would agree... this is empirical for me.  We do a lot of work on
innovation.  Does the creative element, dealing with ambiguity, being
in discovery mode... it's hard to tell.

But empirically I do think it's true.  Women seem to be able to
balance art and engineering more easily.

In this case you have to be a bit of both.  It's not that the
individual needs to be this, the team does.

"My dad was a pilot and my mom was an opera singer."

* When we think about diversity... is this something where future-back thinking might be useful?

E.g., stop treading water and doing the same old things, if we do a
future-back process we can get a breakthrough on it?

If you present forward "We need another woman in Europe..."

- This becomes reactive
- It is just addressing a shortfall now

Instead thinking about in 5 years what do we want to become?

Systems replace systems in terms of transformation.  It's hard to take
an existing system and transform it.  It may be a system problem or a
culture problem.  If we just try to retrofit "make ourselves more
diverse" that's not great.  Rather what do we want to architect.

Similarly to thinking holistically about "core, adjacent and new."

We often retrofit rather than think holistically (to our detriment).

* E.g, in politics..

Partisans are trapped and unable to envision the future.

The race to stop climate change: when you see something like the Paris
accord, is that an example of future-back thinking?

This is a start. It's a goal.  But this is where you need to bring
story telling back to engineering.  "How do you become a practical
visionary?"  Because without the engineering & strategy, the vision
gets lost.

So with 2°, what's the time horizon, you have to work back from the
time horizon.  What do things look like in terms energy composition to
get to that goal?  What do you have to believe in order to make that
happen?  What are the initiatives of today that need to happen?

But basically visionary thinking has to be made practical.

There are plenty of companies that create vision statements!  That's
not what we're talking about.  We need to create a narrative to say
what things look like as we go.

* To implement this

We've talked a lot about future-back envisioning and strategy vs
traditional strategy which tends to be a glorified budgeting process.

Reda McGrath wrote "Seeing Around Corners" talks about how new
ventures need to use a learning process called "emergent planning"
which is about the management of assumptions, including the
assumptions that go into a balance statement.

These things can be invented in an organization, to focus on the
things that support breakthroughs.

If you want to make the change happen, you need to make a commitment
to spend time in the future.  E.g., BMW made a commitment to spend 1
day a quarter talking about the future.  This brings it into the
organization.  This is not about addressing the urgencies of the day
but doing things that are about what they need to address in the
future.
